export const LOADING="LOADING";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";